### ISSUE TITLE
URL platform filtering by status seems broken

### ISSUE THREAD

**Issue by tomlatter** [OceanOPS/webgis#1]
To reproduce: go to //www.ocean-ops.org/maps/interactive/?theme=SOT&ptfStatuses=[2,0]
No platforms are shown on map.

The backward compatibility seems to work (the URL changes and is redirected) but the generated SQL may be somewhat incorrect.

**Comment by anthoninlize** [comment]
Fixed by 4d2b31724189479fb15b33b0620c6b9861ebf884
