### ISSUE TITLE
Potential bug on 'Pin It!' functionality

### ISSUE THREAD

**Issue by tomlatter** [OceanOPS/webgis#2]
For Cruises, after pinnning a cruise sample and then editing cruise sample the new sample get’s "pinned" too. 
This may be intentional, the user (martin) wanted to visualize two cruise samples simulataneosly on the map in two seperate colors, for a screenshot (he pinned the first one) hoping the second would be a different color (unhighlighted).

**Comment by anthoninlize** [comment]
Fixed by 92e089ca6039ee8c0ba8491d2154dcacd4503fc7
